### ISSUE TITLE
Mismatch in test passing/failure vs. Odoo.sh and local Odoo dev installed from sources

### ISSUE THREAD

**Issue by mdurepos** [OCA/oca-ci#68] opened 2024-03-14 13:38 UTC
## Module
oca-ci/py3.8-odoo15.0 package

## Describe the bug
Tests fail on GitHub for both Odoo tests and OCB tests while they pass on Odoo.sh and a local dev instance.

## To Reproduce
**Affected versions**: Unsure (currently latest)

1. Set up a local dev instance and include purchase_delivery_split_date addon from https://github.com/dur-pro/purchase-workflow branch 15.0.
2. Appropriately set up virtual environment and install all required dependencies.
3. Run test suite with `odoo-bin -c <config file> -d <new db name> --test-enable -i purchase_delivery_split_date --stop-after-init`. All tests should pass. Note that running these tests with the version currently on OCA's repo fails 9 tests on dev machine but passes all tests in the GitHub action.
4. See the errors generated from OCA-CI actions here: https://github.com/OCA/purchase-workflow/pull/2203 

**Expected behavior**

Test results should be consistent between Odoo's test suite and the tests run by OCA-CI for the same major version.

**Additional context**

Tests run locally on MacOS with Python 3.8.18, both using only Odoo community edition and full Enterprise edition sources (same result). Tests run on Odoo.sh all passing.

**Comment by sbidoul** [comment] 2024-03-15 18:06
The OCA CI does not run the full Odoo test suite, but pre-installs dependencies of the addons in the repo, then runs the test of only the addons in the repo being tested. This is by design.

**Comment by mdurepos** [comment] 2024-03-15 18:17
@sbidoul This doesn't really explain why OCA CI would fail tests when running more tests passes. Any more input?

**Comment by sbidoul** [comment] 2024-03-15 18:20
Sorry I don't understand what you mean with "why OCA CI would fail tests when running more tests passes".

**Comment by mdurepos** [comment] 2024-03-15 18:24
I think I just understood one nuance I wasn't getting before. If I want to reproduce the test suite being run I would need to run it for ALL the addons in the purchase-workflow repo if I am working on an addon in that repo. If that's the case let's close out this issue and I'll come back if I still have this inconsistent behaviour when doing that.

To be clear, I had been testing with the installation of only the module I was working on (plus any dependencies).

**Comment by sbidoul** [comment] 2024-03-15 18:28
Ah, I see now.

Yes in your PR, the full command is at https://github.com/OCA/purchase-workflow/actions/runs/8280838972/job/22658139982?pr=2203#step:8:15. And that one runs on a db where all the dependencies are pre-installed.

I'm going to close this issue. This is best discussed in the purchase-workflow repo with folks familiar with that repo.

**Closed by sbidoul** 2024-03-15 18:28 UTC
Labels: question
